### ISSUE TITLE
这个界面是咋写的

### ISSUE THREAD

**Issue by TuringHuang** [kingston-csj/chat_client#4]
我想问下这个fx的界面xml文件你是用sceneBuilder写的吗，还是手动写的，对这个不熟，一头雾水，能加QQ聊吗，有些问题想请教，QQ:2398143217

**Comment by kingston-csj** [comment]
是用scenebuilder拖动的，但我对javafx理解也不深。所以客户端效果做得比较慢

**Comment by TuringHuang** [comment]
能不能加下qq，我clone你的代码，有些地方不是太明白，能交流一下吗
